# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.5
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: mulintirohan159@gmail.com
author_name: RohithNai537
contract_name: algoxzencontracts
preset_name: starter
project_name: AlgoXzen-contracts

