# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: mulintirohan159@gmail.com
author_name: RohithNai537
contract_name: contracts
deployment_language: python
preset_name: starter
project_name: AlgoXzen

